# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  BookStoreMVC:
    image: BookStoreMVC
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5175:5175
